mysql:
  address: database-fleetdm.blablabla.us-east-1.rds.amazonaws.com:3306
  database: fleetdm
  username: fleetdm
  password_path: /run/secrets/rds-aws-secret
redis:
  address: redis:6379
server:
  address: 0.0.0.0:8080
  cert: /run/secrets/fleetdm-tls-cert
  key: /run/secrets/fleetdm-tls-key
auth:
  jwt_key_path: /run/secrets/fleetdm-jwt-key
filesystem:
  status_log_file: /tmp/osquery_status
  result_log_file: /tmp/osquery_result
  enable_log_rotation: true
logging:
  json: true
session:
    key_size: 120
    duration: 15m
